server:
  port:
    9095

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

spring:
  application:
    name: FOOD_CATALOG_SERVICE

  data:
    mongodb:
      uri: mongodb://localhost:27017/orderdb
      host: localhost
      port: 27017
      database: orderdb
      repositories:
        enabled: true


